<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return [
	'note' => 'NOTE',
	'tip' => 'TIP',
	'not_available' => 'Not available',
	'mit_license' => 'MIT License',

	'action.back_to_list' => 'Back to the post list',
	'action.browse_admin' => 'Browse backend',
	'action.browse_app' => 'Browse application',
	'action.create_post' => 'Create a new post',
	'action.delete_post' => 'Delete post',
	'action.edit_contents' => 'Edit contents',
	'action.edit_post' => 'Edit post',
	'action.edit' => 'Edit',
	'action.publish_comment' => 'Publish comment',
	'action.save' => 'Save changes',
	'action.show_code' => 'Show code',
	'action.show_post' => 'Show post',
	'action.show' => 'Show',
	'action.sign_in' => 'Sign in',

	'delete_post_modal.body' => 'This action cannot be undone.',
	'delete_post_modal.title' => 'Are you sure you want to delete this post?',

	'help.add_user' => 'If you want to create new users, run this other command:',
	'help.app_description' => 'This is a <strong>demo application</strong> built in the Symfony Framework to illustrate the recommended way of developing Symfony applications.',
	'help.browse_admin' => 'Browse the <strong>admin backend</strong> of the demo application.',
	'help.browse_app' => 'Browse the <strong>public section</strong> of the demo application.',
	'help.login_users' => 'Try either of the following users',
	'help.more_information' => 'For more information, check out the <a href="https://symfony.com/doc">Symfony doc</a>.',
	'help.reload_fixtures' => "If these users don't work, reload application fixtures by running this command from the terminal:",
	'help.role_admin' => 'administrator',
	'help.role_user' => 'regular user',
	'help.show_code' => 'Click on this button to show the source code of the <strong>Controller</strong> and <strong>template</strong> used to render this page.',

	'http_error_403.description' => "You don't have permission to access to this resource.",
	'http_error_403.suggestion' => 'Ask your manager or system administrator to grant you access to this resource.',
	'http_error_404.description' => "We couldn't find the page you requested.",
	'http_error_404.suggestion' => 'Check out any misspelling in the URL or <a href="%url%">go back to the homepage</a>.',
	'http_error_500.suggestion' => 'Try loading this page again in some minutes or <a href="%url%">go back to the homepage</a>.',
	'http_error.description' => 'There was an unknown error (HTTP %status_code%) that prevented to complete your request.',
	'http_error.name' => 'Error %status_code%',
	'http_error.suggestion' => 'Try loading this page again in some minutes or <a href="%url%">go back to the homepage</a>.',

	'label.actions' => 'Actions',
	'label.author_email' => 'Author email',
	'label.author' => 'Author',
	'label.cancel' => 'Cancel',
	'label.content' => 'Content',
	'label.create_post' => 'Create post',
	'label.delete_post' => 'Delete post',
	'label.password' => 'Password',
	'label.published_at' => 'Published at',
	'label.role' => 'Role',
	'label.save_and_create_new' => 'Save and create new',
	'label.summary' => 'Summary',
	'label.tags' => 'Tags',
	'label.title' => 'Title',
	'label.username' => 'Username',

	'menu.admin' => 'Backend',
	'menu.back_to_blog' => 'Back to blog',
	'menu.choose_language' => 'Choose language',
	'menu.homepage' => 'Homepage',
	'menu.logout' => 'Logout',
	'menu.post_list' => 'Post list',
	'menu.rss' => 'Blog Posts RSS',
	'menu.search' => 'Search',
	'menu.toggle_nav' => 'Toggle navigation',

	'notification.comment_created.description' => 'Your post "%title%" has received a new comment. You can read the comment by following <a href="%link%">this link</a>',
	'notification.comment_created' => 'Your post received a comment!',

	'post.commented_on' => 'commented on',
	'post.created_successfully' => 'Post created successfully!',
	'post.deleted_successfully' => 'Post deleted successfully!',
	'post.no_comments' => 'Be the first to comment on this post.',
	'post.no_posts_found' => 'No posts found.',
	'post.num_comments' => '%count% comment|%count% comments',
	'post.search_for' => 'Search for...',
	'post.to_publish_a_comment' => 'to publish a comment',

	'post.updated_successfully' => 'Post updated successfully!',
	'rss.description' => 'Most recent posts published on the Symfony Demo blog',
	'rss.title' => 'Symfony Demo blog',

	'title.add_comment' => 'Add a comment',
	'title.comment_error' => 'There was an error publishing your comment',
	'title.controller_code' => 'Controller code',
	'title.edit_post' => 'Edit post #%id%',
	'title.homepage' => 'Welcome to the <strong>Symfony Demo</strong> application',
	'title.login' => 'Secure Sign in',
	'title.post_list' => 'Post List',
	'title.post_new' => 'Post creation',
	'title.source_code' => 'Source code used to render this page',
	'title.twig_template_code' => 'Twig template code',
];