<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return [
	'comment.blank' => "Please don't leave your comment blank!",
	'comment.is_spam' => 'The content of this comment is considered spam.',
	'comment.too_long' => 'Comment is too long ({{ limit }} characters maximum)',
	'comment.too_short' => 'Comment is too short ({{ limit }} characters minimum)',
	'post.blank_content' => 'Your post should have some content!',
	'post.blank_summary' => 'Give your post a summary!',
	'post.too_many_tags' => 'Too many tags (add {{ limit }} tags or less)',
	'post.too_short_content' => 'Post content is too short ({{ limit }} characters minimum)',
];
