<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return [
	'action.back_to_list' => 'Powrót do listy artykułów',
	'action.browse_admin' => 'Przeglądaj panel administracyjny',
	'action.browse_app' => 'Przeglądaj aplikację',
	'action.create_post' => 'Dodaj nowy artykuł',
	'action.delete_post' => 'Usuń artykuł',
	'action.edit_contents' => 'Edycja treści',
	'action.edit_post' => 'Edytuj artykuł',
	'action.edit' => 'Edytuj',
	'action.publish_comment' => 'Publikuj komentarz',
	'action.save' => 'Zapisz',
	'action.show_code' => 'Pokaż kod',
	'action.show_post' => 'Pokaż artykuł',
	'action.show' => 'Pokaż',
	'action.sign_in' => 'Zaloguj się',

	'delete_post_modal.body' => 'Ta akcja nie może zostać cofnięta.',
	'delete_post_modal.title' => 'Czy na pewno chcesz usunąć ten artykuł?',

	'help.add_user' => 'Jeśli chcesz dodać nowego użytkownika, uruchom następującą komendę:',
	'help.app_description' => 'To jest <strong> przykładowa aplikacja </strong> zbudowana przy pomocy frameworka Symfony, dla zademonstrowania polecanego sposobu tworzenia aplikacji przy jego użyciu.',
	'help.browse_admin' => 'Przeglądaj <strong>panel administracyjny</strong> aplikacji demonstracyjnej.',
	'help.browse_app' => 'Przeglądaj <strong>publiczną część</strong> aplikacji demonstracyjnej.',
	'help.login_users' => 'Użyj dowolnego z poniższych użytkowników',
	'help.more_information' => 'Sprawdź <a href="https://symfony.com/doc">dokumentację Symfony</a>, aby uzyskać więcej informacji.',
	'help.reload_fixtures' => 'Jeśli powyższe dane logowania nie działają, załaduj ponownie przykładowe dane dla tej aplikacji. Uruchom następującą komendę:',
	'help.role_admin' => 'administrator',
	'help.role_user' => 'zwykły użytkownik',
	'help.show_code' => 'Kliknij poniższy przycisk, aby zobaczyć kod <strong>kontrolera</strong> oraz <strong>szablonu</strong> użytych podczas generowania tej podstrony.',
	
	'label.actions' => 'Akcje',
	'label.author_email' => 'Adres e-mail autora',
	'label.author' => 'Autor',
	'label.cancel' => 'Anuluj',
	'label.content' => 'Treść',
	'label.create_post' => 'Dodaj artykuł',
	'label.delete_post' => 'Usuń artykuł',
	'label.password' => 'Hasło',
	'label.published_at' => 'Opublikowano',
	'label.role' => 'Rola',
	'label.save_and_create_new' => 'Zapisz i dodaj kolejny',
	'label.summary' => 'Podsumowanie',
	'label.tags' => 'Etykity',
	'label.title' => 'Tytuł',
	'label.username' => 'Użytkownik',

	'menu.admin' => 'Panel administracyjny',
	'menu.back_to_blog' => 'Powrót do bloga',
	'menu.choose_language' => 'Wybór języka',
	'menu.homepage' => 'Strona główna',
	'menu.logout' => 'Wyloguj się',
	'menu.post_list' => 'Lista artykułów',
	'menu.rss' => 'Blog kanał RSS',
	'menu.search' => 'Szukaj',
	'menu.toggle_nav' => 'Przełącz nawigację',

	'mit_license' => 'Licencja MIT',
	'not_available' => 'Niedostępne',
	'note' => 'UWAGA',

	'post.commented_on' => 'skomentował',
	'post.created_successfully' => 'Artykuł został utworzony!',
	'post.deleted_successfully' => 'Artykuł został usunięty!',
	'post.no_comments' => 'Bądź pierwszym, który skomentuje.',
	'post.no_posts_found' => 'Brak artykułów',
	'post.num_comments' => '%count% komentarz|%count% komentarze|%count% komentarzy',
	'post.search_for' => 'Szukaj w...',
	'post.to_publish_a_comment' => 'aby dodać komentarz',
	'post.updated_successfully' => 'Artykuł został zaktualizowany!',

	'rss.description' => 'Najnowsze publikacje na Symfony Demo blog',
	'rss.title' => 'Aplikacja Symfony Demo',

	'tip' => 'PORADA',
	
	'title.add_comment' => 'Dodaj komentarz',
	'title.comment_error' => 'Podczas publikacji Twojego komentarza wystąpił błąd',
	'title.controller_code' => 'Kod kontrolera',
	'title.edit_post' => 'Edytuj artykuł #%id%',
	'title.homepage' => 'Witamy w aplikacji <strong>Symfony Demo</strong>',
	'title.login' => 'Bezpieczne logowanie',
	'title.post_list' => 'Lista artykułów',
	'title.post_new' => 'Tworzenie nowego artykułu',
	'title.source_code' => 'Kod źródłowy użyty do wygenerowania tej podstrony',
	'title.twig_template_code' => 'Kod szablonu Twig',
];