<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return [
	'comment.blank' => 'Pole komentarza nie może być puste!',
	'comment.is_spam' => 'Twój komentarz został uznany za spam.',
	'comment.too_long' => 'Twój komentarz jest za długi (maksimum: {{ limit }} znaków)',
	'comment.too_short' => 'Twój komentarz jest za krótki (minimum: {{ limit }} znaków)',
	'post.blank_content' => 'Treść artykułu nie może być pusta!',
	'post.blank_summary' => 'Dodaj podsumowanie Twojego artykułu!',
	'post.too_many_tags' => 'Zbyt dużo etykiet (dodaj {{ limit }} lub mniej)',
	'post.too_short_content' => 'Treść artykułu jest za krótka (minimum: {{ limit }} znaków)',
];
